[versions]
kotlin = "1.7.21"
coroutines = "1.6.4"
koin = "3.3.2"
koinAndroid = "3.3.2"
androidGradlePlugin = "7.4.0"

minSdk = "26"
compileSdk = "33"
targetSdk = "33"

androidxActivity = "1.6.1"
androidxAppcompat = "1.6.0"
androidxConstraintLayout = "2.1.4"
androidxCore = "1.9.0"
androidxLifecycle = "2.5.1"
androidxNavigation = "2.5.3"
androidxTestEspresso = "3.5.0"
androidxTestExtJunit = "1.1.4"
junit4 = "4.13.2"
material = "1.8.0"
napier = "2.6.1"

[libraries]
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidxActivity" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidxConstraintLayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidx-lifecycle-compiler = { module = "androidx.lifecycle:lifecycle-compiler", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidxNavigation" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidxNavigation" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidxTestEspresso" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidxTestExtJunit" }
material = { module = "com.google.android.material:material", version.ref = "material" }
napier = { module = "io.github.aakira:napier", version.ref = "napier" }
junit4 = { module = "junit:junit", version.ref = "junit4" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koinAndroid" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test-junit4", version.ref = "koin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

[bundles]
koin = ["koin-android", "koin-core", "koin-test"]
kotlinx-coroutines = ["kotlinx-coroutines-android", "kotlinx-coroutines-core"]

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }