name: Danger

on: workflow_dispatch

jobs:
  danger:
    runs-on: ubuntu-latest
    name: "Run Danger"

    steps:
      - uses: actions/checkout@v3
      - name: Danger
        uses: docker://ghcr.io/danger/danger-kotlin:1.2.0
        with:
          args: --failOnErrors --no-publish-check
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
