name: Release

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Create empty local.properties file
        run: touch local.properties

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Increment version code
        run: ./gradlew incrementVersionCode

      - name: Commit and tag version
        run: |
          git config user.email 'github-actions[bot]'
          git config user.name 'github-actions[bot]@users.noreply.github.com'
          git config push.followTags true
          git add app/version.properties
          versionName=$(./gradlew printVersionName --quiet | tail -n 1)
          git commit -m "Release $versionName"
          git tag -a v$versionName -m "Release $versionName"
          git push

      - name: Run spotless
        run: ./gradlew spotlessCheck

      - name: Build debug variant
        run: ./gradlew assembleDebug

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Setup AppCenter CLI
        run: |
          npm install -g appcenter-cli
          echo "version_code=$(tail -n 1 "app/version.properties" | awk -F'=' ' { print $NF } ')" >> $GITHUB_ENV

      - name: Deploy debug variant to AppCenter
        run: appcenter distribute release --app kyrillosg/Rijksstudio --group "Collaborators" --file "app/build/outputs/apk/debug/rijksstudio-debug-${{ env.version_code }}.apk" --token ${{ secrets.APP_CENTER_TOKEN }}

      - name: Build release variant
        run: ./gradlew assembleRelease

      - name: Run unit tests
        run: ./gradlew testReleaseUnitTest

      - name: Deploy release variant to AppCenter
        run: appcenter distribute release --app kyrillosg/Rijksstudio-1 --group "Collaborators" --file "app/build/outputs/apk/release/rijksstudio-release-${{ env.version_code }}.apk" --token ${{ secrets.APP_CENTER_TOKEN }}
